version: '2'
services:
  nginx:
    container_name: nginx
    build: angular/
    ports: 
      - "80:80"

  springbootservice1:
    container_name: springbootservice1
    build: springCass/
    ports: 
      - "8080"

  zookeeper:
      image: wurstmeister/zookeeper
      ports:
        - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    links:
      - zookeeper:zk
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      
  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    ports:
      - "9000:9000"
    links:
      - zookeeper
      - kafka
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true