sudo: required
language: node_js
node_js:
  - "6"

services:
  - docker

cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run build
  - docker build -t $DOCKER_NAME/angular:newest .
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    docker login --username=$DOCKER_NAME --password=$DOCKER_PW;
    docker push $DOCKER_NAME/angular:newest;
    fi
    